<script lang="ts">
  import { cn } from "$lib/utils";
  import type { Props } from "..";
  import Eye from "~icons/heroicons/eye";
  import EyeSlash from "~icons/heroicons/eye-slash";

  let {
    type = "",
    children,
    class: className,
    inputClass = $bindable(
      "bg-secondary truncate text-on-secondary box-border rounded-3 px-3 py-4 w-full text-[14px] rounded-[12px] px-4 py-3",
    ),
    labelClass = $bindable("text-secondary text-[14px]"),
    classLabel = $bindable(""),
    label = $bindable(undefined),
    value = $bindable(undefined),
    ...rest
  }: Props = $props();

  const inputId = $derived(rest.id ?? "hs-input-" + crypto.randomUUID());

  // --- reactive classes
  let inputCls = $derived(cn(inputClass, className));
  let labelCls = $derived(cn(labelClass, classLabel));

  // --- password toggling
  let showPassword = $state(false);
  function togglePassword() {
    showPassword = !showPassword;
  }
</script>

{#if label !== undefined && type !== "hidden"}
  <label class={labelCls} for={inputId}>{label}</label>
{/if}

{#if type === "password"}
  <div class={cn(inputCls, "relative p-0")}>
    <input
      id={inputId}
      class="w-full pl-4 pr-8 py-3 outline-none"
      bind:value
      type={showPassword ? "text" : "password"}
      {...rest}
    />

    <button
      type="button"
      onclick={togglePassword}
      class="absolute inset-y-0 inset-e-0 z-20 cursor-pointer items-center rounded-e-md px-3 text-on-secondary focus:text-primary focus:outline-none dark:text-white dark:focus:text-blue-500"
      aria-label="Toggle password visibility"
    >
      <!-- eye / eye‑off icon -->
      {#if showPassword}
        <!-- eye‑off -->
        <EyeSlash />
      {:else}
        <!-- eye -->
        <Eye />
      {/if}
    </button>
  </div>
{:else}
  <!-- Plain input -->
  <input class={inputCls} {type} id={inputId} bind:value {...rest} />
{/if}

<!--@component
    - Amaan Dhanani asked TreltaSev for assistance with form inputs
    - TreltaSev responded by making component, generated by SvelteForge🔥
    - Amaan Dhanani is updating it since

    @file Input.svelte
    @description
    A styled text input that supports every native HTML input `type`, with built-in special handling
    for `password` fields: a visibility-toggle button (eye / eye-off icon) is automatically rendered
    inside the field so users can reveal or mask their input. An optional `<label>` is rendered above
    the input when `label` is provided (and the field isn't `type="hidden"`).

    @props
    Extends `HTMLInputAttributes`, so you can pass any native `<input>` attribute (`id`, `name`,
    `placeholder`, `required`, `disabled`, `oninput`, etc.) via `...rest`.

    ### Core Class Props:
    - `inputClass`: Base styling for the input element (and its wrapping div, in password mode).
    - `labelClass`: Base styling for the `<label>` element.

    ### User-Overridable Class Props:
    - `classLabel`: Optional user-defined classes to enhance or override the default `labelClass`.
    - `class`: Native Svelte `class` prop, merged with `inputClass`.

    ### Functional Props:
    - `type`: Native input type (e.g. `"text"`, `"password"`, `"email"`, `"hidden"`). Defaults to `""`.
    - `label`: Optional label text rendered above the input. No label is rendered if left `undefined`.
    - `value`: Bindable input value.
    - `id`: If not provided via `...rest`, a random id (`hs-input-<uuid>`) is generated so the
      `<label for>` association always works.

    @behavior
    - When `type="password"`, the input is wrapped in a relatively-positioned container with a toggle
      button that switches the rendered `type` between `"password"` and `"text"`, swapping the
      eye / eye-off icon to match.
    - For all other types, a single plain `<input>` is rendered.
    - No label is rendered when `type="hidden"`, even if `label` is set.

    @rendered
    An optional `<label>` followed by either a wrapped password input (with toggle button) or a
    plain `<input>` element, depending on `type`.

    @usage
    ```svelte
    <Input label="Email" type="email" bind:value={email} placeholder="you@example.com" />

    <Input label="Password" type="password" bind:value={password} />
    ```
-->
