<script lang="ts">
  import { theme } from "sk-clib/theme";
  import { Frame, Flex, Text } from "sk-clib";
  import Icon from "@iconify/svelte";
  import { cn } from "$lib/utils";
  import { fade } from "svelte/transition";
  import { onMount } from "svelte";
  import { type Props } from "..";

  let {
    text = false,
    btnColor = "secondary",
    iconColor = "on-secondary",
    textColor = "on-surface",
    divClass = "relative",
  }: Props = $props();

  let mounted = $state(false);
  const isDark = $derived(theme.mode === "dark");

  onMount(() => {
    mounted = true;
  });
</script>

{#if mounted}
  <div class={divClass} transition:fade={{ duration: 500 }}>
    <Frame fillw class="gap-10">
      <Flex center class="gap-2">
        <button
          onclick={() => (theme.mode = isDark ? "light" : "dark")}
          class={cn(
            "flex cursor-pointer rounded-full p-3",
            `bg-${btnColor}`,
            `text-${iconColor}`,
          )}
        >
          {#if isDark}
            <Icon
              icon="material-symbols:dark-mode-outline"
              class="size-6"
            />
          {:else}
            <Icon
              icon="material-symbols:light-mode-outline"
              class="size-6"
            />
          {/if}
        </button>

        {#if text}
          <Text class={cn("text-sm select-none", `text-${textColor}`)}>
            {isDark ? "Dark" : "Light"}
          </Text>
        {/if}
      </Flex>
    </Frame>
  </div>
{/if}

<!--@component
    - This component uses theme switching code of TreltaSev's package
    - Requires the use of additional css for theme switching and ThemeInit component.
    - Generated by SvelteForge🔥
    - Amaan Dhanani has updated it since

    @file LightDark.svelte
    @description
    A button that toggles the app's color theme between `light` and `dark` by reading and writing
    the shared `theme.mode` store from `sk-clib/theme`. Renders a sun/moon icon that swaps based on
    the current mode, with an optional text label alongside it.

    @props
    - `text`: Whether to render a "Dark" / "Light" text label next to the icon button. Defaults to `false`.
    - `btnColor`: Background color token applied to the button (e.g. `secondary`, `primary`). Defaults to `'secondary'`.
    - `iconColor`: Color token applied to the icon. Defaults to `'on-secondary'`.
    - `textColor`: Color token applied to the optional text label. Defaults to `'on-surface'`.
    - `divClass`: Class applied to the outer wrapping `<div>`. Defaults to `'relative'`.

    @behavior
    - Reads the current theme from `theme.mode` and derives `isDark` from it.
    - Clicking the button flips `theme.mode` between `'light'` and `'dark'`.
    - The icon swaps between a dark-mode and light-mode glyph depending on the current mode.
    - The whole component is gated behind `onMount`, so it only renders client-side (avoiding
      theme flash / hydration mismatch on SSR) and fades in over 500ms once mounted.

    @rendered
    A `<div>` containing a circular icon button (sun or moon icon depending on theme) and, if
    `text` is `true`, a text label showing "Dark" or "Light".

    @usage
    ```svelte
    <LightDark />

    <LightDark text btnColor="primary" iconColor="on-primary" />
    ```
-->
